### ISSUE TITLE
Unable to install appsync-emulator-serverless

### ISSUE THREAD

**Issue by eerenwong** [ConduitVC/aws-utils#116]
I'm getting error when installing **appsync-emulator-serverless**
by running command `npm i @conduitvc/appsync-emulator-serverless`
Here is the logs:
```
84 verbose stack Error: Non-registry package missing package.json: graphql-phone-type@git+https://github.com/pianomansam/graphql-phone-type.git.
84 verbose stack     at BB.join (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/pacote/lib/finalize-manifest.js:162:23)
84 verbose stack     at tryCatcher (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
84 verbose stack     at Holder$5._callFunction (eval at generateHolderClass (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
84 verbose stack     at Holder$5.checkFulfillment (eval at generateHolderClass (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
84 verbose stack     at Promise.eval (eval at thenCallback (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
84 verbose stack     at Promise._settlePromise (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
84 verbose stack     at Promise._settlePromise0 (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
84 verbose stack     at Promise._settlePromises (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
84 verbose stack     at Promise._fulfill (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
84 verbose stack     at Object.<anonymous> (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21)
84 verbose stack     at emitNone (events.js:111:20)
84 verbose stack     at Object.emit (events.js:208:7)
84 verbose stack     at Object.Parser.on._ (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:75:14)
84 verbose stack     at emitTwo (events.js:126:13)
84 verbose stack     at Object.emit (events.js:214:7)
84 verbose stack     at Object.[emit] (/home/eeren/.nvm/versions/node/v8.16.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:229:12)
85 verbose cwd /home/eeren/Projects/src/consumers
86 verbose Linux 4.18.0-18-generic
87 verbose argv "/home/eeren/.nvm/versions/node/v8.16.0/bin/node" "/home/eeren/.nvm/versions/node/v8.16.0/bin/npm" "i" "@conduitvc/appsync-emulator-serverless"
88 verbose node v8.16.0
89 verbose npm  v6.4.1
90 error code ENOPACKAGEJSON
91 error package.json Non-registry package missing package.json: graphql-phone-type@git+https://github.com/pianomansam/graphql-phone-type.git.
92 error package.json npm can't find a package.json file in your current directory.
93 verbose exit [ 1, true ]
```
Anyone know how to solve it ? Thanks

**Comment by cbaron** [comment]
@eerenwong -- try using `yarn` instead of `npm`

**Comment by lightsofapollo** [comment]
Hrm wondering why we're pointing at a fork here for graphql-phone-type we should fix that... (I think there is an issue for this somewhere)

**Comment by pianomansam** [comment]
> Hrm wondering why we're pointing at a fork here for graphql-phone-type we should fix that... (I think there is an issue for this somewhere)

Here's where I introduced graphql-phone-type: https://github.com/ConduitVC/aws-utils/pull/26

The reason for the fork was to fix a peerDependency issue and to provide a default export within index.js. Here is the diff between forks:

```diff
diff --git a/index.js b/index.js
new file mode 100644
index 0000000..e84adeb
--- /dev/null
+++ b/index.js
@@ -0,0 +1,3 @@
+var GraphQLPhoneType = require('../lib');
+
+export default GraphQLPhoneType;
diff --git a/package.json b/package.json
index eb1698d..d6d38b3 100644
--- a/package.json
+++ b/package.json
@@ -30,7 +30,7 @@
     "libphonenumber-js": "^0.4.43"
   },
   "peerDependencies": {
-    "graphql": "^0.6.0 || ^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0"
+    "graphql": ">=0.6.0 <1.0"
   },
   "devDependencies": {
     "babel-cli": "^6.26.0",
```

**Comment by lightsofapollo** [comment]
Please try `0.12` and see if that works better! I published a few fixes.

**Comment by eerenwong** [comment]
@lightsofapollo I'm using `0.12`. Is workign fine .
Thanks guys
