### ISSUE TITLE
appsync-emulator-serverless TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by devmetal** [ConduitVC/aws-utils#86]
Hi, i faced an issue and it seem to me an implementation error. I use the serverless-appsync-plugin 1.0.9 version, and the latest from appsync-emulator-serverless. The problem is, the latest appsync plugin implemented a feature that i want to use. The feature is the nested mappingTables support.

So i can make a config like this:
```yaml
mappingTemplates:
      - ${file(./src/schema/board/board.mapping.yml)}
      - ${file(./src/schema/ticket/ticket.mapping.yml)}
      - ${file(./src/schema/comment/comment.mapping.yml)}
      - ${file(./src/schema/user/user.mapping.yml)}
```

But when i start this emulator, i got this error instant:
```bash
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at config.mappingTemplates.reduce (/home/adam/works/serverless/aws/graphql-trello-clone-server/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:307:27)
    at Array.reduce (<anonymous>)
    at generateResolvers (/home/adam/works/serverless/aws/graphql-trello-clone-server/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:299:34)
    at createSchema (/home/adam/works/serverless/aws/graphql-trello-clone-server/node_modules/@conduitvc/appsync-emulator-serverless/schema.js:371:27)
    at createSchema (/home/adam/works/serverless/aws/graphql-trello-clone-server/node_modules/@conduitvc/appsync-emulator-serverless/server.js:70:10)
    at <anonymous>
```

So i did a little debug, and the issue is came from the reducer. I loged out the config.mappingTemplates variable, and i found the reduce is not able to work properly because its content:
```javascript
[ [ { dataSource: 'boards',
      type: 'Query',
      field: 'boards',
      request: 'board/mapping/boards-request-mapping-template.txt',
      response: 'board/mapping/boards-response-mapping-template.txt' },
    { dataSource: 'boards',
      type: 'Board',
      field: 'tickets',
      request: 'board/mapping/boards-tickets-request-mapping-template.txt',
      response: 'board/mapping/boards-tickets-response-mapping-template.txt' },
    { dataSource: 'boards',
      type: 'Mutation',
      field: 'createBoard',
      request: 'board/mapping/createBoard-request-mapping-template.txt',
      response: 'board/mapping/createBoard-response-mapping-template.txt' },
    { dataSource: 'boards',
      type: 'Mutation',
      field: 'updateBoard',
      request: 'board/mapping/updateBoard-request-mapping-template.txt',
      response: 'board/mapping/updateBoard-response-mapping-template.txt' },
    { dataSource: 'boards',
      type: 'Mutation',
      field: 'removeBoard',
      request: 'board/mapping/removeBoard-request-mapping-template.txt',
      response: 'board/mapping/removeBoard-response-mapping-template.txt' } ],
  [ { dataSource: 'tickets',
      type: 'Query',
      field: 'ticket',
      request: 'ticket/mapping/ticket-request-mapping-template.txt',
      response: 'ticket/mapping/ticket-response-mapping-template.txt' },
    { dataSource: 'tickets',
      type: 'Ticket',
      field: 'board',
      request: 'ticket/mapping/ticket-board-request-mapping-template.txt',
      response: 'ticket/mapping/ticket-board-response-mapping-template.txt' },
    { dataSource: 'tickets',
      type: 'Ticket',
      field: 'comments',
      request: 'ticket/mapping/ticket-comments-request-mapping-template.txt',
      response: 'ticket/mapping/ticket-comments-response-mapping-template.txt' },
    { dataSource: 'tickets',
      type: 'Mutation',
      field: 'createTicket',
      request: 'ticket/mapping/createTicket-request-mapping-template.txt',
      response: 'ticket/mapping/createTicket-response-mapping-template.txt' },
    { dataSource: 'tickets',
      type: 'Mutation',
      field: 'moveTicket',
      request: 'ticket/mapping/moveTicket-request-mapping-template.txt',
      response: 'ticket/mapping/moveTicket-response-mapping-template.txt' },
    { dataSource: 'tickets',
      type: 'Mutation',
      field: 'updateTicket',
      request: 'ticket/mapping/updateTicket-request-mapping-template.txt',
      response: 'ticket/mapping/updateTicket-response-mapping-template.txt' },
    { dataSource: 'tickets',
      type: 'Mutation',
      field: 'removeTicket',
      request: 'ticket/mapping/removeTicket-request-mapping-template.txt',
      response: 'ticket/mapping/removeTicket-response-mapping-template.txt' } ],
  [ { dataSource: 'comments',
      type: 'Comment',
      field: 'ticket',
      request: 'comment/mapping/comments-ticket-request-mapping-template.txt',
      response: 'comment/mapping/comments-ticket-response-mapping-template.txt' },
    { dataSource: 'comments',
      type: 'Mutation',
      field: 'commentTicket',
      request: 'comment/mapping/commentTicket-request-mapping-template.txt',
      response: 'comment/mapping/commentTicket-response-mapping-template.txt' },
    { dataSource: 'comments',
      type: 'Mutation',
      field: 'updateComment',
      request: 'comment/mapping/updateComment-request-mapping-template.txt',
      response: 'comment/mapping/updateComment-response-mapping-template.txt' },
    { dataSource: 'comments',
      type: 'Mutation',
      field: 'removeComment',
      request: 'comment/mapping/removeComment-request-mapping-template.txt',
      response: 'comment/mapping/removeComment-response-mapping-template.txt' } ],
  [ { dataSource: 'users',
      type: 'Query',
      field: 'users',
      request: 'user/mapping/users-request-mapping-template.txt',
      response: 'user/mapping/users-response-mapping-template.txt' },
    { dataSource: 'users',
      type: 'Mutation',
      field: 'createUser',
      request: 'user/mapping/createUser-request-mapping-template.txt',
      response: 'user/mapping/createUser-response-mapping-template.txt' },
    { dataSource: 'users',
      type: 'Mutation',
      field: 'login',
      request: 'user/mapping/login-request-mapping-template.txt',
      response: 'user/mapping/login-response-mapping-template.txt' },
    { dataSource: 'users',
      type: 'Mutation',
      field: 'validate',
      request: 'user/mapping/validate-request-mapping-template.txt',
      response: 'user/mapping/validate-response-mapping-template.txt' } ] ]
```

It not flatten, and i think it may have to be flattened.
And the configuration is 100% working, because i'm able to deploy to aws.

Thank you for this module and great work!

**Comment by bboure** [comment]
@devmetal I ran into the same issue today.
The problem is indeed that the `mappingTemplates` template is an array of arrays and is not flattened by the emulator like it is by the appsync-plugin

Same problem occurs after implementing this: https://github.com/sid88in/serverless-appsync-plugin/pull/216 for the datasources.

And also when using an object as `datasources` instead of an array: 

````yml
datasources:
  dataName:
    type: type: AWS_LAMBDA
````

**Comment by devmetal** [comment]
@bboure Thank you :) It will be great if we can use same modular structure in data sources as we used in mapping templates :) I think my pr will solve this in appsync emulator. Thank you for support, and thanks for this big improvement in appsync plugin i can't wait to try it :)

**Comment by dirk39** [comment]
Hi guys, I'm facing with this problem right now. Code written by @devmetal solve the problem, but only if you call function `loadConfiguration.js` that flat the `mappingTemplates` property. If you receive a serverless configuration from outside (server.js [line: 44])
```
const createSchema = async ({
  serverless,
  schemaPath = null,
  pubsub,
  dynamodb,
} = {}) => {
  let serverlessConfig = {};
  let serverlessDirectory;
  if (typeof serverless === 'object') {
    serverlessConfig = serverless.service;
    serverlessDirectory = serverless.config.servicePath;
  }
```
You'll receive the same message: `The "path" argument must be of type string. Received type undefined`. I'm thinking to split the part that load configuration from file and move construction and flattening of structure into a new common function (e.g. `normalizeConfiguration`).

What do you think?
